services:
  - type: worker
    name: go-video-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DOWNLOAD_DIR
        value: /app/downloads
      - key: MAX_FILE_SIZE_MB
        value: 50
